[[redirects]]
  from = "/docs/*"
  to = "https://sccmmu.netlify.app/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/blog/*"  
  to = "https://sccmmu.netlify.app/:splat"
  status = 200
  force = false