[[redirects]]
  from = "/html/*"
  to = "https://sccmmu.netlify.app/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/images/*"  
  to = "https://sccmmu.netlify.app/:splat"
  status = 200
  force = false